controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

courses_shortcut:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: app_course_index
        permanent: true